language: python
notifications:
  slack:
    on_success: always
    on_failure: always
  email:
    - OMC-team@cern.ch
    - efol@cern.ch
python:
 - "2.7"
env:
 - EXCITATION=--acd
 - EXCITATION=--adt 
 - EXCITATION= 
script: python GetLLM/getllm_precision_check.py $EXCITATION --optics=40cm
