language: python
notifications:
  email:
    - OMC-team@cern.ch
python:
 - "2.7"
env:
 - EXCITATION=--acd
 - EXCITATION=--adt 
 - EXCITATION= 
script: python GetLLM/getllm_precision_check.py $EXCITATION --optics=40cm
