language: python
email:
    recipients:
      - OMC-team@cern.ch
      - efol@cern.ch
    on_success: always
    on_failure: always
python:
 - "2.7"
script:
 - python tests/alltests.py
 - travis-sphinx build --source=doc/ --nowarn
after_success:
 - travis-sphinx deploy
git:
    depth: false
regression:
    ref_commit: a84dd22837451269a3768476b2bcb714705bcc6f
